pub const HEXPATTERN: &'static str = "^[a-fA-F0-9]*$";
pub const BINPREFIX: &'static str = "0b";
pub const HEXPREFIX: &'static str = "0x";
pub const BINRADIX: usize = 2;
pub const HEXRADIX: usize = 16;
pub const BYTE: usize = 8;
pub const OCTET: usize = 8;
pub const QUADBIT: usize = 4;
pub const BIT: usize = 1;
